HospitalManagement/force-app/main/default/objects/Student__c/fields/Active_Backlogs__c.field-meta.xml
<CustomField>
    <fullName>Active_Backlogs__c</fullName>
    <label>Active Backlogs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

HospitalManagement/force-app/main/default/objects/Student__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

HospitalManagement/force-app/main/default/objects/Student__c/fields/CGPA__c.field-meta.xml
<CustomField>
    <fullName>CGPA__c</fullName>
    <label>CGPA</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

HospitalManagement/force-app/main/default/objects/Student__c/fields/Placement_Status__c.field-meta.xml
<CustomField>
    <fullName>Placement_Status__c</fullName>
    <label>Placement Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Placed</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Placed</fullName>
            </value>
            <value>
                <fullName>Eligible</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

HospitalManagement/force-app/main/default/classes/StudentProfileController.cls
public with sharing class StudentProfileController {

    @AuraEnabled(cacheable=true)
    public static Student__c getStudent(Id studentId) {

        return [
            SELECT Id,
                   Name,
                   Email__c,
                   Phone_Number__c,
                   Branch__c,
                   CGPA__c,
                   Active_Backlogs__c,
                   Placement_Status__c
            FROM Student__c
            WHERE Id = :studentId
            LIMIT 1
        ];
    }

    @AuraEnabled
    public static void updateStudent(
        Id studentId,
        String email,
        String phone,
        String branch,
        Decimal cgpa,
        Integer activeBacklogs
    ) {

        Student__c student = [
            SELECT Id
            FROM Student__c
            WHERE Id = :studentId
            LIMIT 1
        ];

        student.Email__c = email;
        student.Phone_Number__c = phone;
        student.Branch__c = branch;
        student.CGPA__c = cgpa;
        student.Active_Backlogs__c = activeBacklogs;

        update student;
    }
}