HospitalManagement/force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HospitalManagement/force-app/main/default/objects/Application__c/fields/job__c.field-meta.xml
<CustomField>
    <fullName>job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>job</label>
    <referenceTo>job__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

HospitalManagement/force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Offer Accepted</fullName>
            </value>
            <value>
                <fullName>Eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

HospitalManagement/force-app/main/default/objects/job__c/job__c.object-meta.xml
<CustomObject>
    <label>job</label>
    <nameField>
        <label>job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HospitalManagement/force-app/main/default/objects/job__c/fields/closing_date__c.field-meta.xml
<CustomField>
    <fullName>closing_date__c</fullName>
    <label>closing date</label>
    <type>Date</type>
</CustomField>

HospitalManagement/force-app/main/default/objects/job__c/fields/company_name__c.field-meta.xml
<CustomField>
    <fullName>company_name__c</fullName>
    <label>company name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

HospitalManagement/force-app/main/default/objects/job__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CSE</fullName>
            </value>
            <value>
                <fullName>EEE</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>MECh</fullName>
            </value>
            <value>
                <fullName>CIVIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

HospitalManagement/force-app/main/default/objects/job__c/fields/job_Title__c.field-meta.xml
<CustomField>
    <fullName>job_Title__c</fullName>
    <label>job Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

HospitalManagement/force-app/main/default/objects/job__c/fields/Laste_date__c.field-meta.xml
<CustomField>
    <fullName>Laste_date__c</fullName>
    <label>Laste date</label>
    <type>Date</type>
</CustomField>

HospitalManagement/force-app/main/default/objects/job__c/fields/mimnum_cgp__c.field-meta.xml
<CustomField>
    <fullName>mimnum_cgp__c</fullName>
    <label>mimnum cgp</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

HospitalManagement/force-app/main/default/classes/ApplicationController.cls
public with sharing class ApplicationController {

    @AuraEnabled
    public static Id applyForJob(Id studentId, Id jobId) {

        // Get the selected Job
        Job__c job = [
            SELECT Id, company_name__c
            FROM Job__c
            WHERE Id = :jobId
            LIMIT 1
        ];

        // Create Application
        Application__c application = new Application__c();

        application.Student__c = studentId;
        application.Job__c = jobId;
        application.Company_Name__c = job.company_name__c;
        application.Status__c = 'Applied';
        application.Application_Date__c = Date.today();

        insert application;

        return application.Id;
    }


    @AuraEnabled(cacheable=true)
    public static List<Job__c> getJobs() {

        return [
            SELECT Id,
                   Name,
                   company_name__c,
                   job_Title__c,
                   Department__c,
                   closing_date__c,
                   Laste_date__c,
                   mimnum_cgp__c
            FROM Job__c
            ORDER BY closing_date__c ASC
        ];
    }
}